### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pasmax2** [pasmax2/TSX-WEB#1]
[Topic cible](https://www.ts-x.eu/forum/viewtopic.php?p=604071#p604071)

Ce qu'il reste à faire :

- [ ] - Menu angular
- [ ] - Mode actif / passif
- [ ] - Finir les boites des lvl
- [ ] - Mode Telephone carousel
- [ ] - Module IMG event
